---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "yarn.lock"}}
            - v1-npm-{{ .Branch }}
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --non-interactive
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: yarn test
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Install dependencies
          command: |
            yarn global add @oclif/semantic-release@3 semantic-release@15
            yarn --frozen-lockfile
      - run:
          name: Cutting release
          command: |
            export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
            semantic-release -e @oclif/semantic-release
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "grade-git":
    jobs:
      - node-latest
      - node-8
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
